---
- name: host in cluster info demo
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: Gather info about all ESXi Host in the given Cluster
      community.vmware.vmware_host_config_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: "{{ vcenter_validate_certs }}"
        cluster_name: "{{ cluster_name }}"
      register: cluster_info

    - name: print cluster info
      ansible.builtin.debug:
        var: cluster_info
